import { Achievement } from '@/types/achievement';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_step',
    title: 'First Step',
    description: 'Menyelesaikan Morning Reset untuk pertama kalinya.',
    icon: '🌅',
    category: 'habit',
    xpReward: 50,
  },
  {
    id: 'hydration_master',
    title: 'Hydration Master',
    description: 'Mencapai target 8 gelas air dalam satu hari.',
    icon: '💧',
    category: 'habit',
    xpReward: 100,
  },
  {
    id: 'deep_worker',
    title: 'Deep Worker',
    description: 'Fokus lebih dari 100 menit dalam satu hari.',
    icon: '🎯',
    category: 'focus',
    xpReward: 150,
  },
  {
    id: 'focus_beast',
    title: 'Focus Beast',
    description: 'Fokus lebih dari 200 menit dalam satu hari.',
    icon: '🔥',
    category: 'focus',
    xpReward: 250,
  },
  {
    id: 'morning_champion',
    title: 'Morning Champion',
    description: 'Menyelesaikan seluruh Morning Reset.',
    icon: '☀️',
    category: 'habit',
    xpReward: 150,
  },
  {
    id: 'mindfulness_master',
    title: 'Mindfulness Master',
    description: 'Mencatat mood harian dengan kondisi baik (skor >= 4).',
    icon: '💖',
    category: 'special',
    xpReward: 100,
  },
  {
    id: 'screen_time_slayer',
    title: 'Screen Time Slayer',
    description: 'Membatasi screen time maksimal 120 menit sehari.',
    icon: '📱',
    category: 'habit',
    xpReward: 150,
  },
  {
    id: 'loop_breaker',
    title: 'Loop Breaker',
    description: 'Berhasil keluar dan menghancurkan lingkaran prokrastinasi.',
    icon: '🛡️',
    category: 'special',
    xpReward: 200,
  },
  {
    id: 'veteran',
    title: 'Veteran',
    description: 'Mencapai Level 5.',
    icon: '🌟',
    category: 'milestone',
    xpReward: 500,
  },
  {
    id: 'completionist',
    title: 'Completionist',
    description: 'Membuka minimal 5 piala pencapaian.',
    icon: '🏆',
    category: 'milestone',
    xpReward: 300,
  },
  {
    id: 'night_owl_no_more',
    title: 'Night Owl No More',
    description: 'Tidur sebelum jam 23:00 atau mencatat waktu tidur >= 7 jam.',
    icon: '😴',
    category: 'habit',
    xpReward: 100,
  },
  {
    id: 'perfect_day',
    title: 'Perfect Day',
    description: 'Menyelesaikan 16/16 target kebiasaan harian.',
    icon: '👑',
    category: 'special',
    xpReward: 300,
    secret: true,
  }
];
