import { Achievement } from '@/types/achievement';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_step',
    title: 'First Step',
    description: 'Menyelesaikan Morning Reset untuk pertama kalinya.',
    icon: '🌅',
    category: 'habit',
    xpReward: 50,
  },
  {
    id: 'hydration_master',
    title: 'Hydration Master',
    description: 'Mencapai target 8 gelas air dalam satu hari.',
    icon: '💧',
    category: 'habit',
    xpReward: 100,
  },
  {
    id: 'deep_worker',
    title: 'Deep Worker',
    description: 'Fokus lebih dari 100 menit dalam satu hari.',
    icon: '🎯',
    category: 'focus',
    xpReward: 150,
  },
  {
    id: 'focus_beast',
    title: 'Focus Beast',
    description: 'Fokus lebih dari 200 menit dalam satu hari.',
    icon: '🔥',
    category: 'focus',
    xpReward: 250,
  },
  {
    id: 'morning_champion',
    title: 'Morning Champion',
    description: 'Menyelesaikan seluruh Morning Reset.',
    icon: '☀️',
    category: 'habit',
    xpReward: 150,
  },
  {
    id: 'mindfulness_master',
    title: 'Mindfulness Master',
    description: 'Mencatat mood harian dengan kondisi baik (skor >= 4).',
    icon: '💖',
    category: 'special',
    xpReward: 100,
  },
  {
    id: 'screen_time_slayer',
    title: 'Screen Time Slayer',
    description: 'Membatasi screen time maksimal 120 menit sehari.',
    icon: '📱',
    category: 'habit',
    xpReward: 150,
  },
  {
    id: 'loop_breaker',
    title: 'Loop Breaker',
    description: 'Berhasil keluar dan menghancurkan lingkaran prokrastinasi.',
    icon: '🛡️',
    category: 'special',
    xpReward: 200,
  },
  {
    id: 'veteran',
    title: 'Veteran',
    description: 'Mencapai Level 5.',
    icon: '🌟',
    category: 'milestone',
    xpReward: 500,
  },
  {
    id: 'completionist',
    title: 'Completionist',
    description: 'Membuka minimal 5 piala pencapaian.',
    icon: '🏆',
    category: 'milestone',
    xpReward: 300,
  },
  {
    id: 'night_owl_no_more',
    title: 'Night Owl No More',
    description: 'Tidur sebelum jam 23:00 atau mencatat waktu tidur >= 7 jam.',
    icon: '😴',
    category: 'habit',
    xpReward: 100,
  },
  {
    id: 'fajr_ascended',
    title: 'Fajr Ascended',
    description: 'Melakukan sholat subuh tepat waktu selama 7 hari berturut-turut.',
    icon: '🕌',
    category: 'habit',
    xpReward: 200,
  },
  {
    id: 'midnight_caller',
    title: 'Midnight Caller',
    description: 'Mengaktifkan alarm Tahajjud dan menyelesaikan sholat malam Tahajjud.',
    icon: '🌌',
    category: 'special',
    xpReward: 250,
  },
  {
    id: 'perfect_day',
    title: 'Perfect Day',
    description: 'Menyelesaikan 16/16 target kebiasaan harian.',
    icon: '👑',
    category: 'special',
    xpReward: 300,
    secret: true,
  },
  {
    id: 'focus_gladiator',
    title: 'Focus Gladiator',
    description: 'Memenangkan total 5 kali pertarungan fokus di Arena Duel 1v1.',
    icon: '⚔️',
    category: 'focus',
    xpReward: 200,
  },
  {
    id: 'time_alchemist',
    title: 'Time Alchemist',
    description: 'Menyelesaikan seluruh daftar target fokus harian selama 3 hari berturut-turut.',
    icon: '🧪',
    category: 'focus',
    xpReward: 150,
  },
  {
    id: 'dopamine_sovereign',
    title: 'Dopamine Sovereign',
    description: 'Mempertahankan status dopamin tetap "clean" selama 5 hari berturut-turut.',
    icon: '👑',
    category: 'special',
    xpReward: 300,
  },
  {
    id: 'loop_shatterer',
    title: 'Loop Shatterer',
    description: 'Mengaktifkan tombol Break the Loop saat prokrastinasi dan berhasil fokus sesi Pomodoro.',
    icon: '🔨',
    category: 'special',
    xpReward: 150,
  },
  {
    id: 'league_conqueror',
    title: 'Diamond Sovereign',
    description: 'Berhasil menembus liga tertinggi, yaitu Diamond League.',
    icon: '💎',
    category: 'milestone',
    xpReward: 500,
  },
  {
    id: 'multiplier_deity',
    title: 'Multiplier Deity',
    description: 'Mencapai streak kedisiplinan selama 14 hari berturut-turut.',
    icon: '🔥',
    category: 'milestone',
    xpReward: 350,
  },
  {
    id: 'radiant_faith',
    title: 'Radiant Faith',
    description: 'Menyelesaikan sholat Dhuha selama 5 hari berturut-turut.',
    icon: '🌅',
    category: 'habit',
    xpReward: 150,
  },
  {
    id: 'zenith_mind',
    title: 'Zenith Mind',
    description: 'Memulai hari dengan Morning Reset lengkap dan menyelesaikan sholat Dhuha sebelum 09:00.',
    icon: '🧘‍♂️',
    category: 'habit',
    xpReward: 200,
  },
];
