import { HabitDefinition } from '@/types/habit';

export const HABIT_DEFINITIONS: HabitDefinition[] = [
  {
    id: 'sweep',
    label: 'Sweep the House',
    labelId: 'Sapu Rumah',
    description: 'Clean your living space before 07:00',
    category: 'morning',
    icon: '🧹',
    xp: 15,
    deadline: '07:00',
    isMorningLock: true,
  },
  {
    id: 'shower',
    label: 'Take a Shower',
    labelId: 'Mandi',
    description: 'Shower before 08:00 — no phone first',
    category: 'morning',
    icon: '🚿',
    xp: 15,
    deadline: '08:00',
    isMorningLock: true,
  },
  {
    id: 'no_tiktok_morning',
    label: 'No TikTok Morning',
    labelId: 'No TikTok Pagi',
    description: 'No social media scrolling before 09:00',
    category: 'morning',
    icon: '🚫',
    xp: 20,
    deadline: '09:00',
    isMorningLock: true,
  },
  {
    id: 'prayer_fajr',
    label: 'Fajr Prayer',
    labelId: 'Sholat Subuh',
    description: 'Perform Fajr prayer on time',
    category: 'prayer',
    icon: '🕌',
    xp: 25,
    isMorningLock: true,
  },
  {
    id: 'prayer_dhuhr',
    label: 'Dhuhr Prayer',
    labelId: 'Sholat Dzuhur',
    description: 'Perform Dhuhr prayer on time',
    category: 'prayer',
    icon: '🕌',
    xp: 25,
  },
  {
    id: 'prayer_asr',
    label: 'Asr Prayer',
    labelId: 'Sholat Ashar',
    description: 'Perform Asr prayer on time',
    category: 'prayer',
    icon: '🕌',
    xp: 25,
  },
  {
    id: 'prayer_maghrib',
    label: 'Maghrib Prayer',
    labelId: 'Sholat Maghrib',
    description: 'Perform Maghrib prayer on time',
    category: 'prayer',
    icon: '🕌',
    xp: 25,
  },
  {
    id: 'prayer_isya',
    label: 'Isya Prayer',
    labelId: 'Sholat Isya',
    description: "Perform Isya prayer — don't delay",
    category: 'prayer',
    icon: '🕌',
    xp: 25,
  },
  {
    id: 'focus_1h',
    label: '1 Hour Focus',
    labelId: 'Fokus 1 Jam',
    description: 'Deep work session, no distractions',
    category: 'focus',
    icon: '🎯',
    xp: 30,
    deadline: '17:00',
  },
  {
    id: 'meals_4',
    label: '4 Nutritious Meals',
    labelId: 'Makan Lengkap 4 Porsi',
    description: 'Nutritious meals (3x meals + 1x healthy snack)',
    category: 'health',
    icon: '🍽️',
    xp: 20,
    isHidden: true,
  },
  {
    id: 'water_8',
    label: 'Drink 8 Glasses',
    labelId: 'Minum 8 Gelas',
    description: 'Stay hydrated throughout the day',
    category: 'health',
    icon: '💧',
    xp: 20,
    isHidden: true,
  },
  {
    id: 'no_tiktok_night',
    label: 'No TikTok Night',
    labelId: 'No TikTok Malam',
    description: 'No social media after 21:00',
    category: 'night',
    icon: '🌙',
    xp: 20,
  },
  {
    id: 'sleep_before_23',
    label: 'Sleep Before 23:00',
    labelId: 'Tidur Sebelum 23:00',
    description: 'Get to bed by 23:00 for optimal rest',
    category: 'night',
    icon: '😴',
    xp: 25,
    streakBonus: true,
  },
  {
    id: 'freelance_work',
    label: 'Freelance Work',
    labelId: 'Kerja Freelance',
    description: 'Work on design projects today',
    category: 'freelance',
    icon: '💼',
    xp: 25,
  },
];

// Morning lock habits — must complete before dashboard unlocks
export const MORNING_LOCK_HABITS = HABIT_DEFINITIONS
  .filter((h) => h.isMorningLock)
  .map((h) => h.id);

// Habits that count for daily completion percentage
export const DAILY_CORE_HABITS = HABIT_DEFINITIONS.map((h) => h.id);
